name: BlockSpawners
version: '0.0.2'
main: me.duart.blockSpawners.BlockSpawners
api-version: '1.21'
authors: [ DaveDuart ]
description: Simple Block Spawners

commands:
  blockspawners:
    description: BlockSpawners base Command
    aliases: [ bs ]
